name: Run Python Tests
on:
  push:
    branches:
      - test_branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get Env Variables
        run: |
          echo "LM_URL=${{ secrets.LM_URL }}" >> $GITHUB_ENV
          echo "DASHBOARD_NAME=${{ secrets.DASHBOARD_NAME }}" >> $GITHUB_ENV
      - name: Run tests with pytest
        run: pytest

      - name: Check the git build status
        if: job.status == 'success'
        run: |
          echo "test case passed"

      - name: Get Deploy status
        id: Deploy_status
        env:
          deploy_status_value: ${{ job.status }}
        run: echo "$deploy_status_value"


      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"


          # echo "::set-output name=env_url::$ENV_URL"
          # echo ::set-output name=deploy_status_value::$deploy_status_value
          # echo "$deploy_status_value"

# echo "${{ toJson(github) }}"



  email_notification:
    name: EMAIL TESTING
    if: always()
    # needs: [job1, job2]
    # needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: eu-smtp-outbound-1.mimecast.com
          server_port: 25
          username: airflow.awx@global.ntt
          password: ${{ secrets.SMPT_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ deploy_status_value }}
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # html_body: |
          #     <!DOCTYPE html>
          #     <html>
          #     <body>
          #     <h2>Github Response</h2>
          #     <p>Paragraph</p>
          #     </body>
          #     </html>
          to: vigneshraja.muruganantham@global.ntt
          from: github-actions
          ignore_cert: true
          convert_markdown: true
          priority: low