name: Run Python Tests
on:
  push:
    branches:
      - test_branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get Env Variables
        run: |
          echo "LM_URL=${{ secrets.LM_URL }}" >> $GITHUB_ENV
          echo "DASHBOARD_NAME=${{ secrets.DASHBOARD_NAME }}" >> $GITHUB_ENV
      - name: Run tests with pytest
        run: pytest
      - name: Check the git build status
        if: job.status == 'success'
        run: |
          echo "test case passed"


  email_notification:
    name: EMAIL TESTING
    needs: build and test
    runs-on: ubuntu-latest
    steps:
      - name: Send mail  
        run: |
          echo "email part"
        # with:
        #   server_address: "eu-smtp-outbound-1.mimecast.com"
        #   server_port: 465
        #   username: "airflow.awx@global.ntt"
        #   password: "mp.E6mz`\2;,<#U8"
        #   subject: "TEST Mail from github action"
        #   body: Build job of ${{github.repository}} completed successfully!
        #   html_body: |
        #       <!DOCTYPE html>
        #       <html>
        #       <body>
        #       <h1>Heading</h1>
        #       <p>Paragraph</p>
        #       </body>
        #       </html>
        #   to: "vigneshraja.muruganantham@global.ntt"
        #   from: github-actions
        #   # convert_markdown: ${{matrix.convert_markdown}}
        #   priority: low